### PR TITLE
cleanup: pep8, utf8 header, sorted imports, zca decorators, ...

### PR DESCRIPTION
**Pull request by jensens**

### CODE REVIEW

**Comment by gforcada** [comment]
@jensens @thet next time wait until someone from @plone/testing-team creates the job, as I usually have to fix some other code analysis errors.

Job is there: http://jenkins.plone.org/view/Pkgs/job/package-plone.app.relationfield/

**Comment by thet** [comment]
@gforcada that means, for each code style cleanup task we need to create such jenkins jobs?
i know it as best practice from your talk at bucharest...
but is this documented somewhere? would be nice to have it in plone/documentation.

**Comment by gforcada** [comment]
@thet if we want to monitor them yes, a job needs to be created so that it can ping back to GitHub.

I did not document it anywhere as it requires admin-level on plone organization, but anyway it will not hurt to document it.

I usually put jenkins related docs in jenkins itself, so they end up in http://jenkinsploneorg.readthedocs.org/ I will ask the documentation team if it make sense to bring them to docs.plone.org

**Comment by thet** [comment]
@gforcada - not sure if that makes sense for docs.plone.org, although it's also important piece of docs.

@gforcada - @tisto once showed me a draft of a Plone testing & testing culture documentation, which I think isn't integrated in docs.plone.org testing section ( http://docs.plone.org/develop/testing/index.html ). Have you seen such a document? @tisto?

**Comment by gforcada** [comment]
@thet my idea is to add mr.roboto views to let people know how to interact with CI.

Like if you make a pull request it will already mark it as failing if the user that made the pull request is not on github org and point the user to how to sing the CLA.

Also on a pull request we can add a message explaining how to manually test the pull requests (and link to the docs for it). Just like it's already doing with the messages about cleanup that point you on the docs on how to fix them.

**Pull request merged**
